services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_HOST=n8n.ayakdev.web.id
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://n8n.ayakdev.web.id
      - WEBHOOK_URL=https://n8n.ayakdev.web.id
      # Perbaikan untuk deprecation warnings
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    volumes:
      - n8n_n8n_data:/home/node/.n8n

volumes:
  n8n_n8n_data:

